#include <stdlib.h>	// exit...
#include <stdio.h>	// exit...
#include <string.h>	// strcmp, strtok...
#include <stdbool.h>	// true, false...

#define MAX_CMD_LEN 2048
#define MAX_TOK_CNT 16

extern int main(void);
extern bool read_command(char *);
extern bool parse(int, char *[]);
extern bool exec(char *[], char *, char *, int);
